baseURL = 'https://blog.curvemonitor.com/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'lowkey'
title = "Curve Contributors' Blog"
enableRobotsTXT = true
summaryLength = 15
paginate = 5

[outputs]
  home = ['html', 'rss']

[params]
  mainSections = ["posts"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true