[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3

# Social Media Configuration

[[social]]

    identifier = "curvemon"
    name = "CurveMonitor"
    url = "https://www.curvemonitor.com"
    weight = 1

[[social]]

    identifier = "github"
    name = "GitHub"
    url = "https://github.com/curvefi"
    weight = 1